### ISSUE TITLE
Undo Normalize rule that re-enables the Firefox dotted outline

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-reset#3]
```css
button:-moz-focusring,
[type='button']:-moz-focusring,
[type='reset']:-moz-focusring,
[type='submit']:-moz-focusring {
  outline: 0;
}
```
